language: java

jdk:
   - oraclejdk8

services:
   - tomcat

script:
   - mvn cobertura:cobertura  cobertura:cobertura-integration-test test
   - bash <(curl -s https://codecov.io/bash) -t 1iC2Bw6NspnPAM3RKgbHhA


after_success:
   - bash < (curl -s https://codecov.io/bash) -t 1iC2Bw6NspnPAM3RKgbHhA